# Generated by Django 3.2.9 on 2022-03-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addName', models.CharField(max_length=50)),
                ('userId', models.IntegerField(max_length=20)),
                ('addDescription', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
