# Generated by Django 3.2.9 on 2022-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='adds',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
