# Generated by Django 3.2.9 on 2022-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220314_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
