# Generated by Django 3.2.9 on 2022-03-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_adds_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='petCatgory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adds',
            name='addDescription',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='adds',
            name='addName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adds',
            name='userId',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
