# Generated by Django 3.2.9 on 2022-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220315_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='adType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adds',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adds',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adds',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
