# Generated by Django 3.2.9 on 2022-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220415_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
